Algoritmo "CelsiusToFahrenheit"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Douglas de Moura
// Data atual  : 28/10/2019
Var
   c: real
   f: real

Inicio
      Escreval("Temperatura em celsius: ")
      leia(c)
      
      f <- (c * 9/5) + 32
      Escreva("A temperatura em Fahrenheit é de ", f ," graus.")

Fimalgoritmo