Algoritmo "Potencia"
// Disciplina  :  [Linguagem e Lógica de Programação]
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Douglas de Moura
Var
   base,expoente:inteiro


Inicio
   Escreval("*******Programa que calcula potenciacao*******")

   Escreval("Digite a base: ")
   leia(base)

   Escreval("Digite o expoente: ")
   leia(expoente)

   Escreval("Potenciacao: ", base ^ expoente)


Fimalgoritmo