Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Descrição   : Somar dois numeros e exibir a soma...
// Autor(a)    : Douglas de Moura Bezerra
// Data atual  : 28/10/2019
Var
numero1:inteiro
numero2:inteiro
soma:real


Inicio
Escreval("Entre com o primeiro numero: ")
leia(numero1)
Escreval("Entre com o segundo numero: ")
leia(numero2)

soma <- numero1 + numero2

Escreval("A soma dos numeros e: ", soma )

Fimalgoritmo