Algoritmo "SucessorAntecessor"
// Disciplina  :  [Linguagem e Lógica de Programação]
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Douglas de Moura

Var
   numero:inteiro


Inicio
   Escreval("*****Sucessor e antecessor de um numero*****")
   Escreval("Digite um numero:")
   leia(numero)

   Escreval("Sucessor do numero: ", numero + 1)
   Escreval("Antecessor do numero: ", numero - 1)



Fimalgoritmo