Algoritmo "lacoIncondicionalIterativo"
// Disciplina  :  [Linguagem e Lógica de Programação]
//
// Descrição   : [Manzano - exemplo capitulo 5]
// Autor(a)    : Douglas de Moura Bezerra
// Data atual  : 07/11/2019
Var

   r,n,i:inteiro


Inicio

   para i de 1 ate 5 passo 1 faca
      Escreva("Digite um numero: ")
      leia(n)

      r <- n * 3

      Escreval("Resultado: ", r)

   fimpara



Fimalgoritmo