Algoritmo "quadrado_Inteiros"
// Disciplina  :  [Linguagem e Lógica de Programação]
//
// Descrição   : Mostra o quadrado dos numeros inteiros entre 15 e 200
// Autor(a)    : Douglas de Moura Bezerra
// Data atual  : 07/11/2019
Var
   cont:inteiro
   aux:real


Inicio

   Escreval("Quadrado dos inteiros de 15 a 200 ")

   aux <- 0
   para cont de 15 ate 200 passo 1 faca

      aux <- cont ^ 2
      Escreval(cont," a quadrado e: ",aux)

   fimpara


Fimalgoritmo