Algoritmo "tabuada_numero_qualquer_incondicional"
// Disciplina  :  [Linguagem e Lógica de Programação]
//
// Descrição   : Exibir a tabuada de um num qualque de forma tradicional
// Autor(a)    : Douglas de Moura
// Data atual  : 07/11/2019
Var
   n,cont:inteiro


Inicio
   Escreval("Tabuada de um numero")
   Escreval("Digite um numero:")
   leia(n)

   para cont de 1 ate 10 passo 1 faca
      Escreval(n," x ",cont," = ",n * cont)
   fimpara


Fimalgoritmo