Algoritmo "CondicionalSimples"
// Disciplina  :  [Linguagem e Lógica de Programação]
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Douglas de Moura
Var
   a,b,x:inteiro


Inicio
   Escreval("****Desvio condicional Simple****")
   Escreval("Digite um numero para A: ")
   leia(a)

   Escreval("Digite um numero para B: ")
   leia(b)

   x <- a + b

   se(x > 10) entao
      Escreval(x)
   fimse

   Escreval("********Fim do programa********")

Fimalgoritmo