Algoritmo "FAIXA_VALOR_3"
// Disciplina  :  [Linguagem e Lógica de Programação]
//
// Descrição   : APRESENTAR MENSAGEM CASO NUMERO INTEIRO INSERIDO
//SEJA MAIOR QUE TRES USANDO O OPERADOR LOGICO DE NEGACAO
// Autor(a)    : DOUGLAS DE MOURA
// Data atual  : 05/11/2019
Var
   N:INTEIRO


Inicio
   ESCREVAL("DIGITE UM NUMERO INTEIRO: ")
   LEIA(N)

   SE NAO(N > 3) ENTAO
      ESCREVA("VALOR: ",N)
   FIMSE


Fimalgoritmo